### ISSUE TITLE
Ansible) Creating loadbalancer) TypeError: __init__() got an unexpected keyword argument 'dns_ptr'

### ISSUE THREAD

**Issue by mbirchdk** [hetznercloud/hcloud-python#145]
## Bug Report

**Current Behavior**
When running the following ansible-script, i receive the error `TypeError: __init__() got an unexpected keyword argument 'dns_ptr'`. (full stack trace in buttom). 

I can easily create servers and other ressources

Futhermore i cannot find any documentation saying anything about `dns_ptr` in the documentation for creating a loadbalancer, i have looked at the ansible-documentation, and also API-documentation, but did not find anything. 
- https://docs.hetzner.cloud/#load-balancers-create-a-load-balancer
- https://docs.ansible.com/ansible/latest/collections/hetzner/hcloud/hcloud_load_balancer_module.html

**Input Code**
Simple example created to illustrate problem;
`lberror.yml`
```yaml
- hosts: all
  gather_facts: no

  vars_prompt:
    - name: "hetzner_api_token"
      prompt: "Enter api-token from Hetzner"
      private: no

  tasks:
    - name: Create a basic Load Balancer
      hetzner.hcloud.hcloud_load_balancer:
        api_token: "{{ hetzner_api_token }}"
        name: "testlb"
        load_balancer_type: "lb11"
        location: "fsn1"
        state: "present"

```

It is run with command
```
ansible-playbook lberror.yml -e "ansible_python_interpreter=/usr/bin/python3" -vvv
```

**Expected behavior/code**
This script has run before and i expected it to run again when i ran it yesterday - But it does not. I expected it to create a load-balancer in hetzner.

**Environment**
- Python Version: `3.8.10`
- Hcloud-Python Version: Tried with `1.4.3` and also `1.6.0`
- Ansible: `2.10.8`

**Possible Solution**

**Possible relations**
Since my error is dns_ptr on load balancers, it could be related to PR https://github.com/hetznercloud/hcloud-python/pull/144

**Additional context/Screenshots**
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py", line 187, in _get_load_balancer
  File "/home/mikkel/.local/lib/python3.8/site-packages/hcloud/load_balancers/client.py", line 337, in get_by_name
    return super(LoadBalancersClient, self).get_by_name(name)
  File "/home/mikkel/.local/lib/python3.8/site-packages/hcloud/core/client.py", line 75, in get_by_name
    response = self.get_list(name=name)
  File "/home/mikkel/.local/lib/python3.8/site-packages/hcloud/load_balancers/client.py", line 310, in get_list
    ass_load_balancers = [
  File "/home/mikkel/.local/lib/python3.8/site-packages/hcloud/load_balancers/client.py", line 311, in <listcomp>
    BoundLoadBalancer(self, load_balancer_data) for load_balancer_data in response["load_balancers"]
  File "/home/mikkel/.local/lib/python3.8/site-packages/hcloud/load_balancers/client.py", line 29, in __init__
    ipv4_address = IPv4Address(**public_net['ipv4'])
TypeError: __init__() got an unexpected keyword argument 'dns_ptr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mikkel/.ansible/tmp/ansible-tmp-1632291019.7032492-1208449-116182518945343/AnsiballZ_hcloud_load_balancer.py", line 102, in <module>
    _ansiballz_main()
  File "/home/mikkel/.ansible/tmp/ansible-tmp-1632291019.7032492-1208449-116182518945343/AnsiballZ_hcloud_load_balancer.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/mikkel/.ansible/tmp/ansible-tmp-1632291019.7032492-1208449-116182518945343/AnsiballZ_hcloud_load_balancer.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_load_balancer', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py", line 324, in <module>
  File "/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py", line 318, in main
  File "/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py", line 269, in present_load_balancer
  File "/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py", line 191, in _get_load_balancer
AttributeError: 'TypeError' object has no attribute 'message'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py\", line 187, in _get_load_balancer\n  File \"/home/mikkel/.local/lib/python3.8/site-packages/hcloud/load_balancers/client.py\", line 337, in get_by_name\n    return super(LoadBalancersClient, self).get_by_name(name)\n  File \"/home/mikkel/.local/lib/python3.8/site-packages/hcloud/core/client.py\", line 75, in get_by_name\n    response = self.get_list(name=name)\n  File \"/home/mikkel/.local/lib/python3.8/site-packages/hcloud/load_balancers/client.py\", line 310, in get_list\n    ass_load_balancers = [\n  File \"/home/mikkel/.local/lib/python3.8/site-packages/hcloud/load_balancers/client.py\", line 311, in <listcomp>\n    BoundLoadBalancer(self, load_balancer_data) for load_balancer_data in response[\"load_balancers\"]\n  File \"/home/mikkel/.local/lib/python3.8/site-packages/hcloud/load_balancers/client.py\", line 29, in __init__\n    ipv4_address = IPv4Address(**public_net['ipv4'])\nTypeError: __init__() got an unexpected keyword argument 'dns_ptr'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/mikkel/.ansible/tmp/ansible-tmp-1632291019.7032492-1208449-116182518945343/AnsiballZ_hcloud_load_balancer.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/mikkel/.ansible/tmp/ansible-tmp-1632291019.7032492-1208449-116182518945343/AnsiballZ_hcloud_load_balancer.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/mikkel/.ansible/tmp/ansible-tmp-1632291019.7032492-1208449-116182518945343/AnsiballZ_hcloud_load_balancer.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.hetzner.hcloud.plugins.modules.hcloud_load_balancer', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py\", line 324, in <module>\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py\", line 318, in main\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py\", line 269, in present_load_balancer\n  File \"/tmp/ansible_hetzner.hcloud.hcloud_load_balancer_payload_drs_0vnu/ansible_hetzner.hcloud.hcloud_load_balancer_payload.zip/ansible_collections/hetzner/hcloud/plugins/modules/hcloud_load_balancer.py\", line 191, in _get_load_balancer\nAttributeError: 'TypeError' object has no attribute 'message'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}


```

**Comment by LKaemmerling** [comment]
Hey @mbirchdk,

Please make sure that the Python venv from ansible has the latest Hcloud Python Version installed.

**Comment by mbirchdk** [comment]
Hey @LKaemmerling 
Thanks for replying!
I just now realise that it says "hcloud-python version", I got it mixed up with the  ansible hetzner.hcloud-collection-version, where latest version is 1.6.0. 

Anyways! I just upgraded the python module to 1.16.0 and i still receive the same error

**Comment by ieugen** [comment]
I'm getting the same error. 
I just upgraded packages.

```
~/.../infrastructura/ansible$ sudo pip list | grep hcloud
hcloud                   1.16.0
~/.../infrastructura/ansible$ pip list | grep hcloud
hcloud                   1.16.0
~/.../infrastructura/ansible$ pip list | grep ansible
ansible-base             2.10.8
 ansible --version
ansible 2.10.8
  config file = /home/ieugen/.../ansible/ansible.cfg
  configured module search path = ['/home/ieugen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

uname -a
Linux daos-495 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
```
requirements.txt
```
# Used for hetzner dynamic inventory
hcloud==1.16.0
jsondiff
pyyaml>= 3.11
docker
openshift>= 0.6
```

part of requirements.yml
```
collections:
  - name: community.general
    version: 2.5.1
  - name: kubernetes.core
    version: 1.2.1
  - name: community.hrobot
    version: 1.2.0
  - name: hetzner.hcloud
    version: 1.6.0
```

**Comment by ieugen** [comment]
My ansible playbooks are broken for hetzner because of this.
It's not the first time things broke like this for ansible.

**Comment by LKaemmerling** [comment]
@ieugen please make sure that you have the last hcloud-Python installed, even in the venv that Ansible might have created.

**Comment by ieugen** [comment]
thanks. 
I don't use venv , 

For me it fails while getting load balancer info for an existing load balancer.
Load balancer creation works (sort of, the load balancers exist already). 

Maybe it's a bug there.

```
- name: Gather hcloud load_balancer infos
  hetzner.hcloud.hcloud_load_balancer_info:
    api_token: "{{ vault_hetzner_hcloud_token }}"
    name: k1-lb1
  register: lb_result
```

**Comment by LKaemmerling** [comment]
@ieugen if you install Ansible it might create a dedicated venv. Just try the following:

'''
cat $(which ansible) | grep "#!"

**Comment by ieugen** [comment]
```
cat $(which ansible) | grep "#!"
#! /usr/bin/python3
```

**Comment by ieugen** [comment]
I fixed the issue.
The ansible task was executing on another host and I switched to using delegate_to: localhost. 

It's important that the host executing the task has all the dependencies installed. 
I normally have a task that installs the dependencies but this time I did not run it. 

There is no issue with the module.

**Comment by ieugen** [comment]
@mbirchdk make sure the python lib is installed on the machine that calls the ansible module.

I added delegate_to and installed locally.

```
- name: Gather hcloud load_balancer infos
  hetzner.hcloud.hcloud_load_balancer_info:
    api_token: "{{ vault_hetzner_hcloud_token }}"
    name: k2-lb1
  register: lb_result
  delegate_to: localhost
```

**Comment by mbirchdk** [comment]
Hey @ieugen thanks for your input! It made me confident that the problem was solveable

I was also to resolve my problem by updating the hcloud through pip3 with following command; `pip3 install --upgrade hcloud`

Thank you for your help @LKaemmerling and @ieugen ! :)
