### ISSUE TITLE
get volume by id failed

### ISSUE THREAD

**Issue by telsch** [hetznercloud/hcloud-python#16]
## Bug Report

Tried to get volume by id failed:

```python
sys.path.append('/home/user/hcloud-python/')
from hcloud import HcloudClient
client = HcloudClient(token=token)
client.volumes.get_by_id(vol_id)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/hcloud-python/hcloud/volumes/client.py", line 58, in get_by_id
    return BoundVolume(self, response['volume'])
  File "/home/user/hcloud-python/hcloud/volumes/client.py", line 17, in __init__
    super(BoundVolume, self).__init__(client, data, complete)
  File "/home/user/hcloud-python/hcloud/core/client.py", line 69, in __init__
    self.data_model = self.model(**data)
TypeError: __init__() got an unexpected keyword argument 'format'
```

**Environment**
- OS: Ubuntu 18.04.2 LTS
- Python Version: v3.6.7
- Hcloud-Python Version: d80feddf2f205528c5e454420af225e3f93bc16b

**Comment by LKaemmerling** [comment]
Thank you! This should be fixed with  16f33f3
