### ISSUE TITLE
Incompatible ISO8601 format returned by the API 

### ISSUE THREAD

**Issue by jooola** [hetznercloud/hcloud-python#226]
## Bug Report

**Current Behavior**

The [floating IP API documentation](https://docs.hetzner.cloud/#floating-ips-get-all-floating-ips) is using the following ISO8601 format: `2016-01-30T23:55:00+00:00`, but the API currently returns a different ISO8601 format: `2023-06-29T15:37:22Z`.

We recently removed the `python-dateutil` package because we assumed the API will return the format in the documentation (without the `Z`), and use [`datetime.datetime.fromisoformat`](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) to parse the datetime.

Python <3.11 does not support parsing the `2023-06-29T15:37:22Z` ISO8601 format, and this breaks our client for all version of Python <3.11.

**Input Code**

- REPL or Repo link if applicable:

On python 3.9
```python
>>> from datetime import datetime
>>> datetime.fromisoformat("2023-06-29T15:37:22Z")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid isoformat string: '2023-06-29T15:37:22Z'
>>> datetime.fromisoformat("2016-01-30T23:55:00+00:00")
datetime.datetime(2016, 1, 30, 23, 55, tzinfo=datetime.timezone.utc)
```

**Expected behavior/code**

The client should be able to parse the ISO8601 format.

**Environment**

- Python Version: Python 3.9
- Hcloud-Python Version: c821dbe3e2bec59211154dd52bafe3b930945907

**Possible Solution**

- Change the API to return a ISO8601 format parsable by python <3.11. 
- Implement a small wrapper to replace the `Z` with `+00:00`.
- Revert #221, but we probably don't want that.

**Additional context/Screenshots**

- https://github.com/hetznercloud/hcloud-python/pull/221
- https://dev.azure.com/ansible/hetzner.hcloud/_build/results?buildId=82132&view=logs&j=fdb818b8-39d8-529a-d9da-324e304604bc&t=2d52cce2-88ce-5057-da88-145e92cee00f&l=1529

**Comment by jooola** [comment]
The API is also returning ISO8601 datetime with microseconds precision, some of those microseconds precision aren't parsable by `fromisoformat` for python < 3.11.

Example:
`2023-06-30T15:09:46.37719+00:00`
```py

>>> from datetime import datetime, timezone
>>> datetime.fromisoformat('2023-06-30T15:09:46.37719+00:00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid isoformat string: '2023-06-30T15:09:46.37719+00:00'
>>> 
```
